" Name:         CHPASTEL-vim
" Description:  Colorful dark color scheme for Vim based of CHPastel colour scheme
" Author:       Jakub Gawlik <info@caasi.dev>
" Maintainer:   Jakub Gawlik <info@caasi.dev>
" Website:      https://github.com/caasi-dev/vim-chpastel
" License:      This file is placed in the public domain
" Last Updated: Wed 11 Nov 2020 23:43:20 GMT

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'chpastel'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Repeat Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Conditional Statement
hi! link Define PreProc
hi! link Exception Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#282c34', '#c63957', '#5cbb5b', '#d6ab63',
        \ '#648cdd', '#c68ed7', '#46aeb9', '#a2a2a2', '#282c34', '#c63957',
        \ '#5cbb5b', '#d6ab63', '#648cdd', '#c68ed7', '#46aeb9', '#a2a2a2']
  if has('nvim')
    let g:terminal_color_0 = '#282c34'
    let g:terminal_color_1 = '#c63957'
    let g:terminal_color_2 = '#5cbb5b'
    let g:terminal_color_3 = '#d6ab63'
    let g:terminal_color_4 = '#648cdd'
    let g:terminal_color_5 = '#c68ed7'
    let g:terminal_color_6 = '#46aeb9'
    let g:terminal_color_7 = '#a2a2a2'
    let g:terminal_color_8 = '#282c34'
    let g:terminal_color_9 = '#c63957'
    let g:terminal_color_10 = '#5cbb5b'
    let g:terminal_color_11 = '#d6ab63'
    let g:terminal_color_12 = '#648cdd'
    let g:terminal_color_13 = '#c68ed7'
    let g:terminal_color_14 = '#46aeb9'
    let g:terminal_color_15 = '#a2a2a2'
  endif
  if get(g:, 'chpastel_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#a2a2a2 guibg=#282c34 gui=NONE cterm=NONE
    hi CursorLineNr guifg=#a2a2a2 guibg=#282c34 gui=NONE cterm=NONE
    hi FoldColumn guifg=#a2a2a2 guibg=#282c34 gui=NONE cterm=NONE
    hi LineNr guifg=#a2a2a2 guibg=#282c34 gui=NONE cterm=NONE
    hi Terminal guifg=#a2a2a2 guibg=#282c34 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#282c34 gui=NONE cterm=NONE
  hi Conceal guifg=#46aeb9 guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#a2a2a2 guibg=#648cdd gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#282c34 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#282c34 gui=NONE cterm=NONE
  hi DiffAdd guifg=#5cbb5b guibg=#282c34 gui=reverse cterm=reverse
  hi DiffChange guifg=#d6ab63 guibg=#a2a2a2 gui=reverse cterm=reverse
  hi DiffDelete guifg=#c63957 guibg=#a2a2a2 gui=reverse cterm=reverse
  hi DiffText guifg=#5cbb5b guibg=#a2a2a2 gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#5cbb5b guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#282c34 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#c63957 guibg=#a2a2a2 gui=reverse cterm=reverse
  hi Folded guifg=#a2a2a2 guibg=#282c34 gui=italic cterm=italic
  hi IncSearch guifg=#c68ed7 guibg=#a2a2a2 gui=standout cterm=reverse
  hi MatchParen guifg=#282c34 guibg=#d6ab63 gui=bold,reverse cterm=bold,reverse
  hi ModeMsg guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#a2a2a2 guibg=#495d7e gui=NONE cterm=NONE
  hi PmenuSbar guifg=#a2a2a2 guibg=#495d7e gui=NONE cterm=NONE
  hi PmenuSel guifg=#282c34 guibg=#d6ab63 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#282c34 guibg=#d6ab63 gui=NONE cterm=NONE
  hi Question guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#d6ab63 guibg=#a2a2a2 gui=reverse cterm=reverse
  hi SignColumn guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#c68ed7 guibg=NONE guisp=#c68ed7 gui=undercurl cterm=underline
  hi SpellCap guifg=#c68ed7 guibg=NONE guisp=#c68ed7 gui=undercurl cterm=underline
  hi SpellLocal guifg=#c68ed7 guibg=NONE guisp=#c68ed7 gui=undercurl cterm=underline
  hi SpellRare guifg=#c68ed7 guibg=NONE guisp=#c68ed7 gui=undercurl cterm=underline
  hi StatusLine guifg=#46aeb9 guibg=#a2a2a2 gui=reverse cterm=reverse
  hi StatusLineNC guifg=#46aeb9 guibg=#282c34 gui=reverse cterm=reverse
  hi TabLine guifg=#282c34 guibg=#46aeb9 gui=NONE cterm=NONE
  hi TabLineFill guifg=#a2a2a2 guibg=#46aeb9 gui=NONE cterm=NONE
  hi TabLineSel guifg=#a2a2a2 guibg=#46aeb9 gui=NONE cterm=NONE
  hi Title guifg=#d6ab63 guibg=NONE gui=bold cterm=bold
  hi VertSplit guifg=#282c34 guibg=#46aeb9 gui=NONE cterm=NONE
  hi Visual guifg=#648cdd guibg=#a2a2a2 gui=reverse cterm=reverse
  hi VisualNOS guifg=#a2a2a2 guibg=#648cdd gui=NONE cterm=NONE
  hi WarningMsg guifg=#c63957 guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#a2a2a2 guibg=#c68ed7 gui=NONE cterm=NONE
  hi Boolean guifg=#5cbb5b guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#d6ab63 guibg=NONE gui=NONE cterm=NONE
  hi Comment guifg=#495d7e guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#d6ab63 guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#c68ed7 guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#c63957 guibg=#a2a2a2 gui=reverse cterm=reverse
  hi Float guifg=#5cbb5b guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#5cbb5b guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#46aeb9 guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#a2a2a2 guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#c63957 guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#46aeb9 guibg=NONE gui=NONE cterm=NONE
  hi Label guifg=#5cbb5b guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#5cbb5b guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#46aeb9 guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#c68ed7 guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#c68ed7 guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#c68ed7 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#c63957 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#46aeb9 guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#46aeb9 guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#5cbb5b guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#c63957 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#c68ed7 guibg=NONE gui=bold cterm=bold
  hi Type guifg=#c68ed7 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=#a2a2a2 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#282c34 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#46aeb9 guibg=#282c34 gui=bold cterm=bold
  hi NormalMode guifg=#a2a2a2 guibg=#a2a2a2 gui=reverse cterm=reverse
  hi InsertMode guifg=#5cbb5b guibg=#282c34 gui=reverse cterm=reverse
  hi ReplaceMode guifg=#d6ab63 guibg=#282c34 gui=reverse cterm=reverse
  hi VisualMode guifg=#648cdd guibg=#a2a2a2 gui=reverse cterm=reverse
  hi CommandMode guifg=#c68ed7 guibg=#a2a2a2 gui=reverse cterm=reverse
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#a2a2a2 guibg=#a2a2a2 gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'chpastel_transp_bg', 0)
    hi Normal ctermfg=246 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=246 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=246 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=246 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=246 ctermbg=236 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi CursorLineNr ctermfg=246 ctermbg=236 cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=236 cterm=NONE
    hi LineNr ctermfg=246 ctermbg=236 cterm=NONE
    hi Terminal ctermfg=246 ctermbg=236 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi Conceal ctermfg=66 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=246 ctermbg=26 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffAdd ctermfg=71 ctermbg=236 cterm=reverse
  hi DiffChange ctermfg=173 ctermbg=246 cterm=reverse
  hi DiffDelete ctermfg=167 ctermbg=246 cterm=reverse
  hi DiffText ctermfg=71 ctermbg=246 cterm=bold,reverse
  hi Directory ctermfg=71 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=236 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=246 cterm=reverse
  hi Folded ctermfg=246 ctermbg=236 cterm=italic
  hi IncSearch ctermfg=169 ctermbg=246 cterm=reverse
  hi MatchParen ctermfg=236 ctermbg=173 cterm=bold,reverse
  hi ModeMsg ctermfg=246 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=246 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=246 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=246 ctermbg=236 cterm=NONE
  hi PmenuSbar ctermfg=246 ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=236 ctermbg=173 cterm=NONE
  hi PmenuThumb ctermfg=236 ctermbg=173 cterm=NONE
  hi Question ctermfg=246 ctermbg=NONE cterm=NONE
  hi Search ctermfg=173 ctermbg=246 cterm=reverse
  hi SignColumn ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=169 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=169 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=169 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=169 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=66 ctermbg=246 cterm=reverse
  hi StatusLineNC ctermfg=66 ctermbg=236 cterm=reverse
  hi TabLine ctermfg=236 ctermbg=66 cterm=NONE
  hi TabLineFill ctermfg=246 ctermbg=66 cterm=NONE
  hi TabLineSel ctermfg=246 ctermbg=66 cterm=NONE
  hi Title ctermfg=173 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=236 ctermbg=66 cterm=NONE
  hi Visual ctermfg=26 ctermbg=246 cterm=reverse
  hi VisualNOS ctermfg=246 ctermbg=26 cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=246 ctermbg=169 cterm=NONE
  hi Boolean ctermfg=71 ctermbg=NONE cterm=NONE
  hi Character ctermfg=173 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=236 ctermbg=NONE cterm=italic
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=169 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=246 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=246 cterm=reverse
  hi Float ctermfg=71 ctermbg=NONE cterm=NONE
  hi Function ctermfg=71 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=66 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=246 ctermbg=NONE cterm=NONE
  hi Include ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=66 ctermbg=NONE cterm=NONE
  hi Label ctermfg=71 ctermbg=NONE cterm=NONE
  hi Number ctermfg=71 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=66 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=169 ctermbg=NONE cterm=NONE
  hi Special ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=167 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=66 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=66 ctermbg=NONE cterm=NONE
  hi String ctermfg=71 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=167 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=169 ctermbg=NONE cterm=bold
  hi Type ctermfg=169 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=246 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi ToolbarButton ctermfg=66 ctermbg=236 cterm=bold
  hi NormalMode ctermfg=246 ctermbg=246 cterm=reverse
  hi InsertMode ctermfg=71 ctermbg=236 cterm=reverse
  hi ReplaceMode ctermfg=173 ctermbg=236 cterm=reverse
  hi VisualMode ctermfg=26 ctermbg=246 cterm=reverse
  hi CommandMode ctermfg=169 ctermbg=246 cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=246 ctermbg=246 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'chpastel_transp_bg', 0)
    hi Normal ctermfg=Gray ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=Gray ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Gray ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Gray ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=Black cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi Terminal ctermfg=Gray ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi Conceal ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Gray ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=Gray cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi DiffText ctermfg=DarkGreen ctermbg=Gray cterm=bold,reverse
  hi Directory ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi Folded ctermfg=Gray ctermbg=Black cterm=italic
  hi IncSearch ctermfg=DarkMagenta ctermbg=Gray cterm=reverse
  hi MatchParen ctermfg=Black ctermbg=DarkYellow cterm=bold,reverse
  hi ModeMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Gray ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=Gray ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi Question ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkYellow ctermbg=Gray cterm=reverse
  hi SignColumn ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=DarkCyan ctermbg=Gray cterm=reverse
  hi StatusLineNC ctermfg=DarkCyan ctermbg=Black cterm=reverse
  hi TabLine ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi TabLineFill ctermfg=Gray ctermbg=DarkCyan cterm=NONE
  hi TabLineSel ctermfg=Gray ctermbg=DarkCyan cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi Visual ctermfg=DarkBlue ctermbg=Gray cterm=reverse
  hi VisualNOS ctermfg=Gray ctermbg=DarkBlue cterm=NONE
  hi WarningMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=Gray ctermbg=DarkMagenta cterm=NONE
  hi Boolean ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Character ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Black ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Debug ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi Float ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Function ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Include ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Number ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi String ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi Type ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=Gray cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=DarkCyan ctermbg=Black cterm=bold
  hi NormalMode ctermfg=Gray ctermbg=Gray cterm=reverse
  hi InsertMode ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=DarkBlue ctermbg=Gray cterm=reverse
  hi CommandMode ctermfg=DarkMagenta ctermbg=Gray cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=Gray ctermbg=Gray cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: comment              rgb( 73,  93, 126)   236        Black
" Color: black                rgb( 40,  44,  52)   236        Black
" Color: red                  rgb(198,  57,  87)   167        DarkRed
" Color: green                rgb( 92, 187,  91)   71         DarkGreen
" Color: yellow               rgb(214, 171,  99)   173        DarkYellow
" Color: blue                 rgb(100, 140, 221)   26         DarkBlue
" Color: magenta              rgb(198, 142, 215)   169        DarkMagenta
" Color: cyan                 rgb( 70, 174, 185)   66         DarkCyan
" Color: white                rgb(162, 162, 162)   246        Gray
" Term Colors: black red green yellow blue magenta cyan white
" Term Colors: black red green yellow
" Term Colors: blue magenta cyan white
" vim: et ts=2 sw=2
