" Name:         CHPASTEL
" Description:  Colorful dark color scheme for Vim inspired by Apple's CHPASTEL page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-chpastel-theme
" License:      This file is placed in the public domain
" Last Updated: Wed 11 Nov 2020 23:09:11 GMT

" Generated by Colortemplate v2.1.0

set background=dark

hi clear
let g:colors_name = 'chpastel'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Repeat Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Conditional Statement
hi! link Define PreProc
hi! link Exception Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#292c36', '#e64547', '#42a647', '#c98351',
        \ '#4670d8', '#d24e9b', '#64878f', '#949494', '#292c36', '#e64547',
        \ '#42a647', '#c98351', '#4670d8', '#d24e9b', '#64878f', '#949494']
  if has('nvim')
    let g:terminal_color_0 = '#292c36'
    let g:terminal_color_1 = '#e64547'
    let g:terminal_color_2 = '#42a647'
    let g:terminal_color_3 = '#c98351'
    let g:terminal_color_4 = '#4670d8'
    let g:terminal_color_5 = '#d24e9b'
    let g:terminal_color_6 = '#64878f'
    let g:terminal_color_7 = '#949494'
    let g:terminal_color_8 = '#292c36'
    let g:terminal_color_9 = '#e64547'
    let g:terminal_color_10 = '#42a647'
    let g:terminal_color_11 = '#c98351'
    let g:terminal_color_12 = '#4670d8'
    let g:terminal_color_13 = '#d24e9b'
    let g:terminal_color_14 = '#64878f'
    let g:terminal_color_15 = '#949494'
  endif
  if get(g:, 'wwdc16_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#949494 guibg=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#949494 guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#949494 guibg=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#949494 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#949494 guibg=#292c36 gui=NONE cterm=NONE
    hi CursorLineNr guifg=#949494 guibg=#292c36 gui=NONE cterm=NONE
    hi FoldColumn guifg=#949494 guibg=#292c36 gui=NONE cterm=NONE
    hi LineNr guifg=#949494 guibg=#292c36 gui=NONE cterm=NONE
    hi Terminal guifg=#949494 guibg=#292c36 gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#292c36 gui=NONE cterm=NONE
  hi Conceal guifg=#64878f guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#949494 guibg=#4670d8 gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#292c36 gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#292c36 gui=NONE cterm=NONE
  hi DiffAdd guifg=#42a647 guibg=#292c36 gui=reverse cterm=reverse
  hi DiffChange guifg=#c98351 guibg=#949494 gui=reverse cterm=reverse
  hi DiffDelete guifg=#e64547 guibg=#949494 gui=reverse cterm=reverse
  hi DiffText guifg=#42a647 guibg=#949494 gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#292c36 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e64547 guibg=#949494 gui=reverse cterm=reverse
  hi Folded guifg=#949494 guibg=#292c36 gui=italic cterm=italic
  hi IncSearch guifg=#d24e9b guibg=#949494 gui=standout cterm=reverse
  hi MatchParen guifg=#292c36 guibg=#c98351 gui=bold,reverse cterm=bold,reverse
  hi ModeMsg guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#292c36 guibg=#64878f gui=NONE cterm=NONE
  hi PmenuSbar guifg=#292c36 guibg=#292c36 gui=NONE cterm=NONE
  hi PmenuSel guifg=#949494 guibg=#c98351 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#292c36 guibg=#c98351 gui=NONE cterm=NONE
  hi Question guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#c98351 guibg=#949494 gui=reverse cterm=reverse
  hi SignColumn guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#d24e9b guibg=NONE guisp=#d24e9b gui=undercurl cterm=underline
  hi SpellCap guifg=#d24e9b guibg=NONE guisp=#d24e9b gui=undercurl cterm=underline
  hi SpellLocal guifg=#d24e9b guibg=NONE guisp=#d24e9b gui=undercurl cterm=underline
  hi SpellRare guifg=#d24e9b guibg=NONE guisp=#d24e9b gui=undercurl cterm=underline
  hi StatusLine guifg=#64878f guibg=#949494 gui=reverse cterm=reverse
  hi StatusLineNC guifg=#64878f guibg=#292c36 gui=reverse cterm=reverse
  hi TabLine guifg=#292c36 guibg=#64878f gui=NONE cterm=NONE
  hi TabLineFill guifg=#949494 guibg=#64878f gui=NONE cterm=NONE
  hi TabLineSel guifg=#949494 guibg=#64878f gui=NONE cterm=NONE
  hi Title guifg=#c98351 guibg=NONE gui=bold cterm=bold
  hi VertSplit guifg=#292c36 guibg=#64878f gui=NONE cterm=NONE
  hi Visual guifg=#4670d8 guibg=#949494 gui=reverse cterm=reverse
  hi VisualNOS guifg=#949494 guibg=#4670d8 gui=NONE cterm=NONE
  hi WarningMsg guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#949494 guibg=#d24e9b gui=NONE cterm=NONE
  hi Boolean guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#c98351 guibg=NONE gui=NONE cterm=NONE
  hi Comment guifg=#949494 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#c98351 guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#e64547 guibg=#949494 gui=reverse cterm=reverse
  hi Float guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#64878f guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#64878f guibg=NONE gui=NONE cterm=NONE
  hi Label guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#64878f guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#64878f guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#64878f guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#d24e9b guibg=NONE gui=bold cterm=bold
  hi Type guifg=#d24e9b guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=#949494 gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#292c36 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#64878f guibg=#292c36 gui=bold cterm=bold
  hi NormalMode guifg=#949494 guibg=#949494 gui=reverse cterm=reverse
  hi InsertMode guifg=#42a647 guibg=#292c36 gui=reverse cterm=reverse
  hi ReplaceMode guifg=#c98351 guibg=#292c36 gui=reverse cterm=reverse
  hi VisualMode guifg=#4670d8 guibg=#949494 gui=reverse cterm=reverse
  hi CommandMode guifg=#d24e9b guibg=#949494 gui=reverse cterm=reverse
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#949494 guibg=#949494 gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=246 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=246 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=246 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=246 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=246 ctermbg=236 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi CursorLineNr ctermfg=246 ctermbg=236 cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=236 cterm=NONE
    hi LineNr ctermfg=246 ctermbg=236 cterm=NONE
    hi Terminal ctermfg=246 ctermbg=236 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi Conceal ctermfg=66 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=246 ctermbg=26 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffAdd ctermfg=71 ctermbg=236 cterm=reverse
  hi DiffChange ctermfg=173 ctermbg=246 cterm=reverse
  hi DiffDelete ctermfg=167 ctermbg=246 cterm=reverse
  hi DiffText ctermfg=71 ctermbg=246 cterm=bold,reverse
  hi Directory ctermfg=71 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=236 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=246 cterm=reverse
  hi Folded ctermfg=246 ctermbg=236 cterm=italic
  hi IncSearch ctermfg=169 ctermbg=246 cterm=reverse
  hi MatchParen ctermfg=236 ctermbg=173 cterm=bold,reverse
  hi ModeMsg ctermfg=246 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=246 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=246 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=236 ctermbg=66 cterm=NONE
  hi PmenuSbar ctermfg=236 ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=246 ctermbg=173 cterm=NONE
  hi PmenuThumb ctermfg=236 ctermbg=173 cterm=NONE
  hi Question ctermfg=246 ctermbg=NONE cterm=NONE
  hi Search ctermfg=173 ctermbg=246 cterm=reverse
  hi SignColumn ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=169 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=169 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=169 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=169 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=66 ctermbg=246 cterm=reverse
  hi StatusLineNC ctermfg=66 ctermbg=236 cterm=reverse
  hi TabLine ctermfg=236 ctermbg=66 cterm=NONE
  hi TabLineFill ctermfg=246 ctermbg=66 cterm=NONE
  hi TabLineSel ctermfg=246 ctermbg=66 cterm=NONE
  hi Title ctermfg=173 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=236 ctermbg=66 cterm=NONE
  hi Visual ctermfg=26 ctermbg=246 cterm=reverse
  hi VisualNOS ctermfg=246 ctermbg=26 cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=246 ctermbg=169 cterm=NONE
  hi Boolean ctermfg=71 ctermbg=NONE cterm=NONE
  hi Character ctermfg=173 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=246 ctermbg=NONE cterm=italic
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=169 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=246 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=246 cterm=reverse
  hi Float ctermfg=71 ctermbg=NONE cterm=NONE
  hi Function ctermfg=71 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=66 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=246 ctermbg=NONE cterm=NONE
  hi Include ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=66 ctermbg=NONE cterm=NONE
  hi Label ctermfg=71 ctermbg=NONE cterm=NONE
  hi Number ctermfg=71 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=66 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=169 ctermbg=NONE cterm=NONE
  hi Special ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=167 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=66 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=66 ctermbg=NONE cterm=NONE
  hi String ctermfg=71 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=167 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=169 ctermbg=NONE cterm=bold
  hi Type ctermfg=169 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=246 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi ToolbarButton ctermfg=66 ctermbg=236 cterm=bold
  hi NormalMode ctermfg=246 ctermbg=246 cterm=reverse
  hi InsertMode ctermfg=71 ctermbg=236 cterm=reverse
  hi ReplaceMode ctermfg=173 ctermbg=236 cterm=reverse
  hi VisualMode ctermfg=26 ctermbg=246 cterm=reverse
  hi CommandMode ctermfg=169 ctermbg=246 cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=246 ctermbg=246 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=Gray ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=Gray ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Gray ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=Gray ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=Black cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi Terminal ctermfg=Gray ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi Conceal ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=Gray ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=Gray cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi DiffText ctermfg=DarkGreen ctermbg=Gray cterm=bold,reverse
  hi Directory ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi Folded ctermfg=Gray ctermbg=Black cterm=italic
  hi IncSearch ctermfg=DarkMagenta ctermbg=Gray cterm=reverse
  hi MatchParen ctermfg=Black ctermbg=DarkYellow cterm=bold,reverse
  hi ModeMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi NonText ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi PmenuSbar ctermfg=Black ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=Gray ctermbg=DarkYellow cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=DarkYellow cterm=NONE
  hi Question ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkYellow ctermbg=Gray cterm=reverse
  hi SignColumn ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=DarkCyan ctermbg=Gray cterm=reverse
  hi StatusLineNC ctermfg=DarkCyan ctermbg=Black cterm=reverse
  hi TabLine ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi TabLineFill ctermfg=Gray ctermbg=DarkCyan cterm=NONE
  hi TabLineSel ctermfg=Gray ctermbg=DarkCyan cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi Visual ctermfg=DarkBlue ctermbg=Gray cterm=reverse
  hi VisualNOS ctermfg=Gray ctermbg=DarkBlue cterm=NONE
  hi WarningMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=Gray ctermbg=DarkMagenta cterm=NONE
  hi Boolean ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Character ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Debug ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=Gray cterm=reverse
  hi Float ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Function ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Include ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Number ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi String ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi Type ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=Gray cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=DarkCyan ctermbg=Black cterm=bold
  hi NormalMode ctermfg=Gray ctermbg=Gray cterm=reverse
  hi InsertMode ctermfg=DarkGreen ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=DarkBlue ctermbg=Gray cterm=reverse
  hi CommandMode ctermfg=DarkMagenta ctermbg=Gray cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=Gray ctermbg=Gray cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                rgb( 41,  44,  54)   236        Black
" Color: red                  rgb(230,  69,  71)   167        DarkRed
" Color: green                rgb( 66, 166,  71)   71         DarkGreen
" Color: yellow               rgb(201, 131,  81)   173        DarkYellow
" Color: blue                 rgb( 70, 112, 216)   26         DarkBlue
" Color: magenta              rgb(210,  78, 155)   169        DarkMagenta
" Color: cyan                 rgb(100, 135, 143)   66         DarkCyan
" Color: white                rgb(148, 148, 148)   246        Gray
" Term Colors: black red green yellow blue magenta cyan white
" Term Colors: black red green yellow
" Term Colors: blue magenta cyan white
" vim: et ts=2 sw=2
